### ISSUE TITLE
Wrap parenthesis descrepancy

### ISSUE THREAD

**Issue by Zygahedron** [balt-is-you-and-shift/robot-is-chill#33]
The help text when searching for wrap says `wrap<int>/<int>` but the actual usage is `wrap(<int>/<int>)`.
I suggest removing the parenthesis from the usage to make it consistent with almost everything else.
(Ideally crop and warp shouldn't have them either, or everything should have them, but that's a separate issue)

**Comment by balt-is-you-and-shift** [comment]
i removed them from all of them except warp since i need the parentheses to be able to keep track of what's what
