### ISSUE TITLE
../ and ./ can be used in palettes to view any image

### ISSUE THREAD

**Issue by 3DG** [balt-is-you-and-shift/robot-is-chill#37]
Example: =pal ../sprites/bab/bab_0_1 gives a picture of bab

With this bug, you can view any image on whoever runs the bot's PC provided that you know the path to the image from the palettes folder.

**Comment by balt-is-you-and-shift** [comment]
O_O oh my god thanks for telling me

**Comment by balt-is-you-and-shift** [comment]
resolved '._.
