### ISSUE TITLE
-m, scale, crop not working together right

### ISSUE THREAD

**Issue by steadyventure** [balt-is-you-and-shift/robot-is-chill#41]
Hello, it seems that when combined, -m and scale cause the order of values to be rearranged for cropping. the command i found this from was `=tile -m=5 plate:scale2&tuto:black:scale2:crop0/12/24/24`, the expected result would be to crop tuto to make it only show the smile, but instead it cut off the right half of the sprite. I've included an image of the result i got below.

![render_2022-02-23_17 56 00](https://user-images.githubusercontent.com/100309560/155381928-856b7a64-0aeb-4d26-8cee-2ef4db9a3e24.gif)

**Comment by balt-is-you-and-shift** [comment]
it seems to be just :scale

**Comment by balt-is-you-and-shift** [comment]
nothing's actually wrong, you just need to adjust your values for :crop
