### ISSUE TITLE
"combine" flag breaks following flags

### ISSUE THREAD

**Issue by prismacrafter** [balt-is-you-and-shift/robot-is-chill#47]
i tried doing `=tile -c -g=1 baba:face:blank&baba:main:o!missing`, and the bot returned with the error of `The tile -g=1 could not be found.` i then tried `=tile -g=1 -c baba:face:blank&baba:main:o!missing`, and it worked.

**Comment by AndyThatBeDizzy** [comment]
this is not an issue with global specifically, it seems that variants just dont work when placed after -c
![image](https://user-images.githubusercontent.com/76802512/158493433-56ec0760-aa5e-46f5-856d-f3e18f05efc5.png)

**Comment by prismacrafter** [comment]
i see

very good to know

**Comment by balt-is-you-and-shift** [comment]
i don't know if this is fixed or not now that variants have been rewritten
i'll test when i can

**Comment by balt-is-you-and-shift** [comment]
works now!
