### ISSUE TITLE
Transparent objects with -b affect the background

### ISSUE THREAD

**Issue by AndyThatBeDizzy** [balt-is-you-and-shift/robot-is-chill#48]
![1](https://user-images.githubusercontent.com/76802512/158642376-60745d66-4d1b-422a-951d-3cd56f985991.png)
![2](https://user-images.githubusercontent.com/76802512/158643426-688e2f60-1468-4e6a-8907-74ce96188939.png)

two examples of this happening
this is probably only a thing because it wasn't accounted for when there were only gif renders, due to no partial transparency

**Comment by balt-is-you-and-shift** [comment]
`=tile -b=#ff0000 baba:scale8:opacity0.5`
![render_2022-03-16_17.22.07.gif](https://user-images.githubusercontent.com/59123926/158650201-bde7c2ba-0b34-4ebf-9271-f9c3b36a68a6.gif)
I can't reproduce this.

**Comment by balt-is-you-and-shift** [comment]
Nevermind, I see, it's an issue with PNG encoding. Strange. I'll look at it when I can.

**Comment by balt-is-you-and-shift** [comment]
Agh, fixing this is gonna be messy.

**Comment by balt-is-you-and-shift** [comment]
Fixed, although renders are less performant now, since I have to alpha composite, and that's slow compared to pasting.
