### ISSUE TITLE
Mirror variant is broken

### ISSUE THREAD

**Issue by AndyThatBeDizzy** [balt-is-you-and-shift/robot-is-chill#49]
![render_2022-03-19_23 31 11](https://user-images.githubusercontent.com/76802512/159142852-9369c769-c682-4f21-b26e-b59aeb7a799a.gif)
the variants depicted in the render are x/front, x/back, y/front, and y/back from top to bottom 
x/front is also mirrored vertically, x/back looks fine, y/back and/y front just dont work at all

**Comment by CenTdemeern1** [comment]
I'll look into this later (probably)

**Comment by balt-is-you-and-shift** [comment]
forgot to close this after fixing lmao
