### ISSUE TITLE
Hex values incorrect

### ISSUE THREAD

**Issue by trancatabby** [balt-is-you-and-shift/robot-is-chill#65]
The hex values are broken and I don’t know why.

I download a GIF and take a screenshot of a game I’m playing — i’m trying to figure out what hex values the palette colors are.

Apparently, every website that I check for color picking and things like that say the same thing:
Something is… not right with this hex code.

![6CF81A67-3DDA-4C3A-9769-EB4D779EAB97](https://user-images.githubusercontent.com/106228186/170201061-97cb5034-90cf-41f2-be51-dab9bba3582a.jpeg)

I’m not sure if it’s my fault for screenshotting it, or downloading the gif, or just not doing it as a PNG or something, but if you can fix it I would like you to.

Sincerely,
<sup>The ~~blue~~ #2561ff, ~~yellow~~ #fefd02, and ~~orange~~ #fe8c00 cat</sup>

**Comment by balt-is-you-and-shift** [comment]
this is a limitation of pil iirc, for some reason hex codes are just barely off with gifs
there's not much i can do to fix this, sorry
