### ISSUE TITLE
colselect with numbers more than one digit doesn't work properly

### ISSUE THREAD

**Issue by AndyThatBeDizzy** [balt-is-you-and-shift/robot-is-chill#67]
as an example, before, `debug:c13` used to give the white part of debug. i have no idea what it's doing now 
![image](https://user-images.githubusercontent.com/76802512/173658747-55c205b3-18b1-481c-ab81-49ab1ebad3bc.png)

**Comment by balt-is-you-and-shift** [comment]
fixed
