### ISSUE TITLE
Couldn't DM the bot

### ISSUE THREAD

**Issue by SteamrollinLowFloor** [balt-is-you-and-shift/robot-is-chill#69]
For some reason I can't dm the bot.
![image](https://user-images.githubusercontent.com/108910954/177901749-678bc9bb-223e-46b8-8136-5f94ea04f978.png)

**Comment by AndyThatBeDizzy** [comment]
this might be an issue on your end and not the bots end, it seems to be working fine

**Comment by SteamrollinLowFloor** [comment]
Yeah Something odd is going on

**Comment by CenTdemeern1** [comment]
Do you share a server with the bot?

**Comment by SteamrollinLowFloor** [comment]
I haven't been able to DM the bot since 6/10/22
Now Clyde isn't trusting the About me page on The bot

**Comment by SteamrollinLowFloor** [comment]
Is there by chance the bot blocked me?

**Comment by Megaclpb** [comment]
Do you have "Allow direct messages from server members." enabled in one of those servers

**Comment by SteamrollinLowFloor** [comment]
Yes

**Comment by balt-is-you-and-shift** [comment]
whatever this is, it's not fixable by us
