### ISSUE TITLE
Gradient Bug

### ISSUE THREAD

**Issue by Loapher19** [balt-is-you-and-shift/robot-is-chill#74]
gradient keeps crashing and i cant figure out why

**Comment by balt-is-you-and-shift** [comment]
Uh. Can you give a reproduction example, aka a command I can run to test this?

**Comment by Loapher19** [comment]
=tile pixel:gradientx0/24/1/0

**Comment by balt-is-you-and-shift** [comment]
Fixed! Thanks for telling me.
